title: Arjuna
domain: arjunacluster.github.io
url: https://arjunacluster.github.io
baseurl: /ArjunaUsers/

theme: "just-the-docs"
color_scheme: "light"
search_enabled: true

ga_tracking: G-X2LPWRLJ7X
