name: Password Reset
description: Forgot your Arjuna Password?
title: Password Reset
labels:
  - "admin-tasks"

body:
  - type: input
    attributes:
      label: Andrew ID
      description: "Enter your AndrewID"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Next steps
        You will receive an email from `the Arjuna Admins <root@coe.psc.edu` with your new login information within 10 business days.
        If you do not, please comment on this issue, ***do not open another issue***

        In the meantime, checkout our documentation [https://arjunacluster.github.io/ArjunaUsers/]()
